---
- name: move interface to vagrantvrf
  lineinfile:
    path: /etc/network/interfaces
    insertafter: 'iface vagrant inet dhcp'
    line: '    vrf vagrantvrf'
  notify: reload networking
  tags:
    - vagrantvrf
  #when: ansible_vagrant is defined
...
